---
# yamllint disable rule:line-length
- name: Check latest version
  ansible.builtin.uri:
    url: https://api.github.com/repos/mvdan/sh/releases/latest
  register: shfmt_latest

- name: Create bin directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/bin"
    state: directory
    mode: "0755"

- name: Download latest shfmt_latest
  ansible.builtin.get_url:
    url: "{{ shfmt_latest.json | community.general.json_query(app_image_query) | first }}" # noqa jinja[invalid]
    dest: "{{ ansible_facts['user_dir'] }}/bin/shfmt"
    mode: "0755"
  vars:
    app_image_query: "assets[?ends_with(name,'linux_amd64')].browser_download_url"
